apiVersion: v1
kind: Service
metadata:
  name: in-cluster-pg-hostname # 이 이름이 서비스의 호스트주소가 됨
spec:
  type: LoadBalancer
  # type: NodePort
  selector:
    app: postgres-database # pod 에서 설정한 선택자
  ports:
    - port: 5432
      targetPort: 5432
