apiVersion: v1
kind: Pod
metadata:
  name: node
  labels:
    app: node-pod
spec:
  containers:
    - name: node
      image: node
      command: ['sleep', '3600']
      env:
        - name: POSTGRES_PASSWORD
          value: '1234'
  # nodeName: instance-1 (hostname) 마스터노드에서 실행할 경우,,
