apiVersion: v1
kind: Pod
metadata:
  name: pg # pod 이름
  labels:
    app: postgres
spec:
  containers:
    - name: pg
      image: postgres # 도커 이미지 이름
      env: # 환경변수
        - name: POSTGRES_PASSWORD
          value: '1234'
      ports:
        - containerPort: 5432
          name: pg
  # nodeName: instance-1 (hostname) 마스터노드에서 실행할 경우,,
