apiVersion: v1
kind: Pod
metadata:
  name: pg
  labels:
    app: postgres
spec:
  containers:
    - name: pg
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: '1234'
      ports:
        - containerPort: 5432
          name: pg
