apiVersion: v1
kind: Pod
metadata:
  name: py
  labels:
    app: python-pod
spec:
  containers:
    - name: py
      image: python
      command: ['sleep', '3600']
      env:
        - name: POSTGRES_PASSWORD
          value: '1234'
  # nodeName: instance-1 (hostname) 마스터노드에서 실행할 경우,,
