apiVersion: v1
kind: Pod
metadata:
  name: r
  labels:
    app: r-pod
spec:
  containers:
    - name: r
      image: r-base
      command: ['sleep', '7200'] # 컨테이너 구동시 실행할 명령어
      env:
        - name: POSTGRES_PASSWORD
          value: '1234'
  # nodeName: instance-1 (hostname) 마스터노드에서 실행할 경우,,
